### ISSUE TITLE
User Story 2.3 - Code Snippets via CodeMirror

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/cse110-sp24-group10#48]
# As a developer, I want to be able to save code snippets in my journal

## Overview
Currently, the Journal page has a button which switches the view of the text box, but we want to fully implement what we have planned out in the design (as attached in the image below) and allow the user to type into a code editor window, which will be implemented with CodeMirror.

## Technical Specifics
CodeMirror is a library which provides an easy way to integrate a code editor component for your web application. Take a look at the documentation for how to implement: [https://codemirror.net](https://codemirror.net). Also focus on getting a very simple code box component working for now before looking into adding features such as support for more languages or autocompletion.

<img width="782" alt="Screenshot 2024-05-28 at 12 11 12 AM" src="https://github.com/cse110-sp24-group10/cse110-sp24-group10/assets/75578029/1b15a451-5767-4ead-83b4-b2b43bed6e2d">

## Definition of Done
We will know this user story is complete when:
- Clicking on the `code` button in the Journal page switches the text box to a code box which implements a working CodeMirror component, which has support for ATLEAST JavaScript. (If time allows team can look into support for other languages)
- This code is locally saved (switching to text and back to code will not get rid of the code)

**Comment by mic051** [comment]
definition of done complete with codemirror 5
