### ISSUE TITLE
User Story 2.5 - Integrating Tasks with Journal

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/cse110-sp24-group10#50]
# As a user, I want my journal to be synced with my task list

## Overview
Currently, the journal displays hardcoded tasks, but we want our users to have the tasks within their task list show up on the journal in a simplified way. 

## Technical Details
In order to complete this, communication with the Task List team might be necessary to figure out how the tasks are being stored within the LocalStorage. From there, pulling the tasks from the LocalStorage for the **current day** will be necessary. 

Once the tasks for the current day are retrieved, on the Journal side we will want to display the task name, the difficulty, and the status. If the status is changed in the journal, we will also want to update it on the task list, and vice versa.

## Definition of Done
We will know this user story is done when:
- The tasks from the task list show up for some specific day on the Journal
- Checking off a task in the journal will check it off as complete in the task list, and vice versa

**Comment by pprabu-ucsd** [comment]
Tasks properly displayed in journal
