### ISSUE TITLE
Adding Languages and Themes for Code Editor

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/cse110-sp24-group10#69]
We want to add a dropdown to allow the user to select different coding languages in the CodeMirror component, as well as a couple of different themes that are built into CodeMirror version 5. This should be able to be completed by just changing the `editor.mode` as well as the `editor.theme`.

**Comment by anishcd** [comment]
Done but needs to be merged

**Comment by mic051** [comment]
Merged, code was in journal-codemirror
